[build]
builder = "nixpacks"
buildCommand = "python -m pip install -r requirements-deploy.txt"

[deploy]
startCommand = "python -m uvicorn backend.api:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
